/**
 * Python 3 intelligence data used by the Monaco completion provider.
 *
 * Everything here is static and offline so autocomplete works instantly on
 * both the web build (Pyodide) and the native Android build (Chaquopy).
 * A lazy Jedi pass (see pyodide-runner) can layer deeper suggestions on top
 * once the Python runtime is loaded.
 */

/** Top-level standard-library module names, suggested after `import`. */
export const PYTHON_STDLIB_MODULES: string[] = [
  "abc",
  "argparse",
  "array",
  "ast",
  "asyncio",
  "base64",
  "bisect",
  "builtins",
  "calendar",
  "collections",
  "concurrent.futures",
  "configparser",
  "contextlib",
  "copy",
  "csv",
  "ctypes",
  "dataclasses",
  "datetime",
  "decimal",
  "difflib",
  "dis",
  "email",
  "enum",
  "errno",
  "filecmp",
  "fnmatch",
  "fractions",
  "functools",
  "gc",
  "getpass",
  "gettext",
  "glob",
  "gzip",
  "hashlib",
  "heapq",
  "hmac",
  "html",
  "http.client",
  "http.server",
  "importlib",
  "inspect",
  "io",
  "ipaddress",
  "itertools",
  "json",
  "keyword",
  "linecache",
  "locale",
  "logging",
  "lzma",
  "math",
  "mimetypes",
  "multiprocessing",
  "numbers",
  "operator",
  "os",
  "os.path",
  "pathlib",
  "pickle",
  "pkgutil",
  "platform",
  "pprint",
  "queue",
  "random",
  "re",
  "secrets",
  "shelve",
  "shlex",
  "shutil",
  "signal",
  "smtplib",
  "socket",
  "socketserver",
  "sqlite3",
  "ssl",
  "statistics",
  "string",
  "struct",
  "subprocess",
  "sys",
  "sysconfig",
  "tarfile",
  "tempfile",
  "textwrap",
  "threading",
  "time",
  "timeit",
  "token",
  "tokenize",
  "traceback",
  "tracemalloc",
  "types",
  "typing",
  "unicodedata",
  "unittest",
  "urllib.error",
  "urllib.parse",
  "urllib.request",
  "uuid",
  "warnings",
  "wave",
  "weakref",
  "webbrowser",
  "xml.etree.ElementTree",
  "zipfile",
  "zlib",
  "zoneinfo",
];

/**
 * Members of well-known modules. Entries may include a short signature hint
 * (e.g. "sqrt(x) -> float"); the completion label is the part before "(".
 */
export const PYTHON_MODULE_MEMBERS: Record<string, string[]> = {
  math: [
    "pi", "e", "tau", "inf", "nan",
    "sqrt(x) -> float", "pow(x, y) -> float", "exp(x) -> float",
    "log(x[, base]) -> float", "log2(x) -> float", "log10(x) -> float",
    "sin(x) -> float", "cos(x) -> float", "tan(x) -> float",
    "asin(x) -> float", "acos(x) -> float", "atan(x) -> float",
    "atan2(y, x) -> float", "sinh(x) -> float", "cosh(x) -> float",
    "tanh(x) -> float", "degrees(x) -> float", "radians(x) -> float",
    "floor(x) -> int", "ceil(x) -> int", "trunc(x) -> int",
    "fabs(x) -> float", "factorial(n) -> int", "gcd(*ints) -> int",
    "lcm(*ints) -> int", "isclose(a, b) -> bool", "isfinite(x) -> bool",
    "isinf(x) -> bool", "isnan(x) -> bool", "fsum(iterable) -> float",
    "prod(iterable) -> number", "comb(n, k) -> int", "perm(n, k) -> int",
    "hypot(*coords) -> float", "copysign(x, y) -> float", "fmod(x, y) -> float",
    "remainder(x, y) -> float", "dist(p, q) -> float", "cbrt(x) -> float",
    "math.comb", "math.perm",
  ],
  random: [
    "random() -> float", "randint(a, b) -> int", "randrange(start, stop[, step]) -> int",
    "uniform(a, b) -> float", "choice(seq)", "choices(population, k=1)",
    "shuffle(seq)", "sample(population, k)", "seed(a=None)",
    "gauss(mu, sigma) -> float", "normalvariate(mu, sigma) -> float",
    "expovariate(lambd) -> float", "betavariate(alpha, beta) -> float",
    "triangular(low, high, mode) -> float", "getrandbits(k) -> int",
  ],
  os: [
    "getcwd() -> str", "chdir(path)", "listdir(path='.')", "mkdir(path[, mode])",
    "makedirs(name[, mode])", "remove(path)", "rmdir(path)", "renames(old, new)",
    "rename(src, dst)", "replace(src, dst)", "stat(path)", "walk(top)",
    "sep", "linesep", "name", "environ", "getenv(key[, default])",
    "putenv(key, value)", "system(command)", "popen(command)", "urandom(n)",
    "cpu_count() -> int", "getpid() -> int", "path",
  ],
  "os.path": [
    "join(path, *paths) -> str", "exists(path) -> bool", "isfile(path) -> bool",
    "isdir(path) -> bool", "islink(path) -> bool", "abspath(path) -> str",
    "basename(path) -> str", "dirname(path) -> str", "splitext(path) -> tuple",
    "split(path) -> tuple", "getsize(path) -> int", "getmtime(path) -> float",
    "normpath(path) -> str", "relpath(path[, start]) -> str",
    "realpath(path) -> str", "expanduser(path) -> str", "commonprefix(list) -> str",
  ],
  sys: [
    "argv", "exit([code])", "path", "modules", "version", "version_info",
    "platform", "maxsize", "stdin", "stdout", "stderr", "exc_info()",
    "getsizeof(obj) -> int", "setrecursionlimit(limit)", "getrecursionlimit() -> int",
    "executable", "flags", "byteorder", "implementation",
  ],
  json: [
    "dumps(obj, indent=None) -> str", "loads(s)", "dump(obj, fp)",
    "load(fp)", "JSONDecodeError", "JSONEncoder", "JSONDecoder",
  ],
  time: [
    "time() -> float", "sleep(seconds)", "ctime([secs]) -> str",
    "localtime([secs])", "gmtime([secs])", "strftime(format[, t]) -> str",
    "strptime(string, format)", "mktime(t) -> float", "monotonic() -> float",
    "perf_counter() -> float", "process_time() -> float", "asctime([t]) -> str",
    "timezone", "struct_time", "tzname",
  ],
  datetime: [
    "datetime", "date", "time", "timedelta", "timezone", "tzinfo",
    "MINYEAR", "MAXYEAR", "UTC",
  ],
  "datetime.datetime": [
    "now([tz])", "today()", "utcnow()", "strptime(date_string, format)",
    "fromtimestamp(timestamp[, tz])", "combine(date, time)",
    "isoformat([sep])", "timestamp()", "date()", "time()", "weekday()",
    "strftime(format) -> str", "replace(...)",
  ],
  "datetime.timedelta": [
    "days", "seconds", "microseconds", "total_seconds() -> float",
    "timedelta(days=0, seconds=0, microseconds=0)",
  ],
  re: [
    "compile(pattern[, flags])", "search(pattern, string)", "match(pattern, string)",
    "fullmatch(pattern, string)", "findall(pattern, string) -> list",
    "finditer(pattern, string)", "sub(pattern, repl, string) -> str",
    "subn(pattern, repl, string) -> tuple", "split(pattern, string) -> list",
    "escape(pattern) -> str", "purge()", "IGNORECASE", "MULTILINE", "DOTALL",
    "VERBOSE", "ASCII", "UNICODE", "Pattern", "Match", "error",
  ],
  collections: [
    "OrderedDict", "defaultdict", "Counter", "deque", "namedtuple",
    "ChainMap", "UserDict", "UserList", "UserString",
  ],
  itertools: [
    "count(start, step=1)", "cycle(iterable)", "repeat(obj[, times])",
    "chain(*iterables)", "compress(data, selectors)", "dropwhile(pred, it)",
    "takewhile(pred, it)", "filterfalse(pred, it)", "groupby(iterable, key)",
    "islice(iterable, stop)", "starmap(func, iterable)", "tee(iterable, n=2)",
    "zip_longest(*iterables)", "product(*iterables)", "permutations(iterable, r)",
    "combinations(iterable, r)", "combinations_with_replacement(iterable, r)",
    "accumulate(iterable)", "batched(iterable, n)", "pairwise(iterable)",
  ],
  functools: [
    "reduce(func, iterable[, init])", "partial(func, *args, **kwargs)",
    "wraps(wrapped)", "lru_cache(maxsize=128)", "cache", "cached_property",
    "cmp_to_key(func)", "total_ordering", "singledispatch", "update_wrapper",
  ],
  pathlib: [
    "Path", "PurePath", "PurePosixPath", "PureWindowsPath", "PosixPath",
    "WindowsPath",
  ],
  string: [
    "ascii_letters", "ascii_lowercase", "ascii_uppercase", "digits",
    "hexdigits", "octdigits", "punctuation", "printable", "whitespace",
    "capwords(s) -> str", "Template", "Formatter",
  ],
  statistics: [
    "mean(data) -> float", "median(data)", "mode(data)", "multimode(data)",
    "stdev(data) -> float", "pstdev(data) -> float", "variance(data) -> float",
    "pvariance(data) -> float", "median_low(data)", "median_high(data)",
    "median_grouped(data)", "quantiles(data, n)", "fmean(data) -> float",
    "geometric_mean(data) -> float", "harmonic_mean(data) -> float",
    "correlation(x, y)", "covariance(x, y)", "linear_regression(x, y)",
  ],
  typing: [
    "List", "Dict", "Set", "Tuple", "Optional", "Union", "Any", "Callable",
    "Iterable", "Iterator", "Sequence", "Mapping", "MutableMapping",
    "TypeVar", "Generic", "Protocol", "Literal", "Final", "ClassVar",
    "TypedDict", "NamedTuple", "cast", "overload", "get_type_hints",
    "NewType", "runtime_checkable", "Annotated", "TypeAlias", "Self",
  ],
  urllib: ["parse", "request", "error", "robotparser"],
  "urllib.parse": [
    "quote(string)", "unquote(string)", "urlencode(query)", "urlparse(url)",
    "urljoin(base, url)", "urlsplit(url)", "parse_qs(qs)", "parse_qsl(qs)",
    "quote_plus(string)", "unquote_plus(string)", "urlunparse(parts)",
  ],
  "urllib.request": [
    "urlopen(url)", "urlretrieve(url, filename)", "Request(url)",
    "build_opener(*handlers)", "install_opener(opener)", "pathname2url(path)",
    "HTTPBasicAuthHandler", "ProxyHandler",
  ],
  csv: [
    "reader(csvfile)", "writer(csvfile)", "DictReader(f)", "DictWriter(f, fieldnames)",
    "register_dialect(name)", "get_dialect(name)", "field_size_limit([new_limit])",
    "QUOTE_ALL", "QUOTE_MINIMAL", "QUOTE_NONNUMERIC", "QUOTE_NONE", "Error",
    "Dialect", "excel", "excel_tab", "unix_dialect",
  ],
  sqlite3: [
    "connect(database)", "Connection", "Cursor", "Row", "Error", "DatabaseError",
    "IntegrityError", "OperationalError", "ProgrammingError", "PARSE_DECLTYPES",
    "PARSE_COLNAMES", "version", "sqlite_version", "Binary",
    "complete_statement(sql)", "register_adapter(type, adapter)",
    "register_converter(typename, converter)",
  ],
  threading: [
    "Thread", "Lock", "RLock", "Event", "Condition", "Semaphore",
    "BoundedSemaphore", "Barrier", "Timer", "current_thread()",
    "active_count() -> int", "enumerate()", "get_ident() -> int", "local",
    "main_thread()", "settrace(func)",
  ],
  subprocess: [
    "run(args)", "Popen(args)", "call(args)", "check_call(args)",
    "check_output(args)", "PIPE", "STDOUT", "DEVNULL", "CompletedProcess",
    "TimeoutExpired", "CalledProcessError",
  ],
  hashlib: [
    "md5(data)", "sha1(data)", "sha224(data)", "sha256(data)", "sha384(data)",
    "sha512(data)", "sha3_256(data)", "sha3_512(data)", "blake2b(data)",
    "blake2s(data)", "new(name)", "algorithms_available", "algorithms_guaranteed",
  ],
  base64: [
    "b64encode(s)", "b64decode(s)", "urlsafe_b64encode(s)", "urlsafe_b64decode(s)",
    "b32encode(s)", "b32decode(s)", "b16encode(s)", "b16decode(s)",
    "a85encode(s)", "a85decode(s)", "standard_b64encode(s)",
  ],
  tempfile: [
    "TemporaryFile()", "NamedTemporaryFile()", "TemporaryDirectory()",
    "mkstemp()", "mkdtemp()", "gettempdir() -> str", "gettempprefix() -> str",
  ],
  glob: ["glob(pattern) -> list", "iglob(pattern)", "escape(pathname)", "has_magic(pathname)"],
  shutil: [
    "copy(src, dst)", "copy2(src, dst)", "copyfile(src, dst)", "copytree(src, dst)",
    "move(src, dst)", "rmtree(path)", "make_archive(base, fmt, root)",
    "unpack_archive(filename)", "which(cmd)", "disk_usage(path)",
    "get_terminal_size()",
  ],
  pickle: [
    "dump(obj, file)", "dumps(obj)", "load(file)", "loads(data)", "Pickler",
    "Unpickler", "HIGHEST_PROTOCOL", "DEFAULT_PROTOCOL",
  ],
  argparse: ["ArgumentParser", "Namespace", "Action", "FileType"],
  logging: [
    "getLogger(name=None)", "basicConfig()", "debug(msg)", "info(msg)",
    "warning(msg)", "error(msg)", "critical(msg)", "exception(msg)",
    "log(level, msg)", "Logger", "Handler", "StreamHandler", "FileHandler",
    "Formatter", "NOTSET", "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL",
  ],
  decimal: [
    "Decimal(value)", "getcontext()", "setcontext(ctx)", "localcontext(ctx)",
    "Context", "InvalidOperation", "DivisionByZero", "ROUND_HALF_UP", "ROUND_DOWN",
  ],
  enum: ["Enum", "IntEnum", "StrEnum", "Flag", "IntFlag", "auto", "unique", "member", "nonmember"],
  dataclasses: [
    "dataclass", "field", "asdict(instance)", "astuple(instance)",
    "make_dataclass(name, fields)", "replace(instance, **changes)",
    "is_dataclass(obj)", "FrozenInstanceError", "fields(class_or_instance)",
    "InitVar", "KW_ONLY",
  ],
  contextlib: [
    "contextmanager", "closing(thing)", "suppress(*exceptions)",
    "redirect_stdout(target)", "redirect_stderr(target)", "ExitStack",
    "nullcontext(enter_result=None)", "asynccontextmanager",
  ],
  copy: ["copy(x)", "deepcopy(x)", "Error"],
  uuid: [
    "uuid1()", "uuid3(namespace, name)", "uuid4()", "uuid5(namespace, name)",
    "UUID", "NAMESPACE_DNS", "NAMESPACE_URL", "NAMESPACE_OID", "NAMESPACE_X500",
  ],
  io: ["StringIO", "BytesIO", "open(file)", "TextIOWrapper", "BufferedReader", "BufferedWriter"],
  queue: ["Queue", "LifoQueue", "PriorityQueue", "SimpleQueue", "Empty", "Full"],
  heapq: [
    "heappush(heap, item)", "heappop(heap)", "heapify(x)", "heapreplace(heap, item)",
    "heappushpop(heap, item)", "nlargest(n, iterable)", "nsmallest(n, iterable)",
    "merge(*iterables)",
  ],
  operator: [
    "itemgetter(item)", "attrgetter(attr)", "methodcaller(name)", "add(a, b)",
    "sub(a, b)", "mul(a, b)", "truediv(a, b)", "floordiv(a, b)", "mod(a, b)",
    "pow(a, b)", "eq(a, b)", "ne(a, b)", "lt(a, b)", "le(a, b)", "gt(a, b)",
    "ge(a, b)", "and_(a, b)", "or_(a, b)", "not_(a)", "contains(a, b)",
    "index(a)", "concat(a, b)", "length_hint(obj)",
  ],
  unicodedata: [
    "normalize(form, unistr)", "name(chr)", "lookup(name)", "category(chr)",
    "bidirectional(chr)", "combining(chr)", "decimal(chr)", "digit(chr)",
    "numeric(chr)", "east_asian_width(chr)",
  ],
  platform: [
    "system() -> str", "node() -> str", "release() -> str", "version() -> str",
    "machine() -> str", "processor() -> str", "python_version() -> str",
    "python_implementation() -> str", "platform() -> str", "architecture()",
    "uname()",
  ],
  getpass: ["getpass([prompt])", "getuser() -> str"],
  pprint: ["pprint(object)", "pformat(object) -> str", "PrettyPrinter"],
  fractions: ["Fraction(numerator=0, denominator=1)"],
  weakref: ["ref(object)", "proxy(object)", "WeakValueDictionary", "WeakKeyDictionary", "WeakSet", "finalize(obj)"],
  asyncio: [
    "run(coro)", "create_task(coro)", "sleep(delay)", "gather(*coros)",
    "wait(fs)", "wait_for(fut, timeout)", "Queue", "Event", "Lock",
    "Semaphore", "Task", "Future", "get_event_loop()", "new_event_loop()",
  ],
  "concurrent.futures": [
    "ThreadPoolExecutor", "ProcessPoolExecutor", "as_completed(fs)", "wait(fs)",
    "Future", "TimeoutError",
  ],
  multiprocessing: ["Process", "Pool", "Queue", "Pipe", "Manager", "cpu_count()", "current_process()"],
  socket: [
    "socket(family, type)", "AF_INET", "AF_INET6", "SOCK_STREAM", "SOCK_DGRAM",
    "SOL_SOCKET", "SO_REUSEADDR", "gethostname()", "getaddrinfo(host, port)",
    "gethostbyname(host)", "create_connection(address)",
  ],
  "http.client": ["HTTPConnection(host)", "HTTPSConnection(host)", "HTTPResponse"],
  smtplib: ["SMTP(host)", "SMTP_SSL(host)", "SMTPException"],
  ssl: ["create_default_context()", "SSLContext", "wrap_socket(sock)", "CERT_NONE", "CERT_REQUIRED"],
  struct: ["pack(fmt, *values)", "unpack(fmt, buffer)", "calcsize(fmt)", "Struct(fmt)", "pack_into(fmt, buf, offset, *values)", "unpack_from(fmt, buf, offset=0)"],
  bisect: ["bisect(a, x)", "bisect_left(a, x)", "bisect_right(a, x)", "insort(a, x)", "insort_left(a, x)", "insort_right(a, x)"],
  sysconfig: ["get_paths()", "get_config_var(name)", "get_python_version()", "get_config_vars()"],
  signal: ["signal(signum, handler)", "SIGINT", "SIGTERM", "SIGKILL", "alarm(seconds)", "pause()", "getsignal(signum)", "SIG_IGN", "SIG_DFL"],
  gc: ["collect() -> int", "get_objects()", "disable()", "enable()", "isenabled() -> bool", "get_referrers(*objs)", "get_referents(*objs)", "garbage"],
  inspect: [
    "getsource(object)", "getmembers(object)", "getfile(object)", "getdoc(object)",
    "signature(callable)", "isfunction(object)", "isclass(object)", "ismethod(object)",
    "stack()", "currentframe()", "getfullargspec(func)", "getmodule(object)",
  ],
  warnings: ["warn(message)", "filterwarnings(action)", "simplefilter(action)", "catch_warnings()", "Warning"],
  calendar: [
    "month(theyear, themonth)", "calendar(theyear)", "isleap(year) -> bool",
    "leapdays(y1, y2)", "monthrange(year, month)", "weekday(year, month, day)",
    "monthcalendar(year, month)", "TextCalendar", "HTMLCalendar", "day_name",
    "month_name",
  ],
  difflib: ["SequenceMatcher", "Differ", "unified_diff(a, b)", "ndiff(a, b)", "get_close_matches(word, possibilities)", "HtmlDiff"],
  textwrap: ["wrap(text, width=70)", "fill(text, width=70)", "shorten(text, width)", "dedent(text)", "indent(text, prefix)", "TextWrapper"],
  fnmatch: ["fnmatch(name, pat) -> bool", "fnmatchcase(name, pat) -> bool", "filter(names, pat)", "translate(pat)"],
  zlib: ["compress(data)", "decompress(data)", "crc32(data)", "adler32(data)"],
  gzip: ["compress(data)", "decompress(data)", "open(filename)", "GzipFile"],
  zipfile: ["ZipFile(file)", "ZipInfo", "is_zipfile(filename)", "ZIP_STORED", "ZIP_DEFLATED"],
  tarfile: ["open(name)", "TarFile", "getmembers()", "extractall(path)"],
  secrets: ["token_bytes(nbytes=None)", "token_hex(nbytes=None)", "token_urlsafe(nbytes=None)", "randbelow(n)", "choice(seq)", "compare_digest(a, b)", "randbits(k)"],
  ipaddress: ["ip_address(address)", "ip_network(address)", "ip_interface(address)", "IPv4Address", "IPv6Address", "IPv4Network", "IPv6Network"],
  numbers: ["Number", "Complex", "Real", "Rational", "Integral"],
  abc: ["ABC", "ABCMeta", "abstractmethod", "abstractproperty", "get_cache_token()", "update_abstractmethods(cls)"],
  ast: ["parse(source)", "literal_eval(node)", "dump(node)", "walk(node)", "NodeVisitor", "NodeTransformer", "FunctionDef", "ClassDef", "unparse(ast_obj)"],
  importlib: ["import_module(name)", "reload(module)", "invalidate_caches()", "metadata", "util", "resources"],
  types: ["SimpleNamespace", "MappingProxyType", "ModuleType", "FunctionType", "MethodType", "GeneratorType", "coroutine", "new_class(name)", "DynamicClassAttribute"],
};

/** Python builtins with a short signature hint, shown in ordinary code. */
export const PYTHON_BUILTINS: Record<string, string> = {
  abs: "abs(x) -> number",
  aiter: "aiter(async_iterable)",
  all: "all(iterable) -> bool",
  anext: "anext(async_iterator[, default])",
  any: "any(iterable) -> bool",
  ascii: "ascii(obj) -> str",
  bin: "bin(x) -> str",
  bool: "bool(x=False)",
  breakpoint: "breakpoint(*args, **kwargs)",
  bytearray: "bytearray([source[, encoding]])",
  bytes: "bytes([source[, encoding]])",
  callable: "callable(obj) -> bool",
  chr: "chr(i) -> str",
  classmethod: "classmethod(function)",
  compile: "compile(source, filename, mode)",
  complex: "complex(real=0, imag=0)",
  delattr: "delattr(obj, name)",
  dict: "dict(**kwargs)",
  dir: "dir([object]) -> list",
  divmod: "divmod(a, b) -> tuple",
  enumerate: "enumerate(iterable, start=0)",
  eval: "eval(expression[, globals[, locals]])",
  exec: "exec(source[, globals[, locals]])",
  filter: "filter(function, iterable)",
  float: "float(x=0.0)",
  format: "format(value[, format_spec]) -> str",
  frozenset: "frozenset([iterable])",
  getattr: "getattr(object, name[, default])",
  globals: "globals() -> dict",
  hasattr: "hasattr(object, name) -> bool",
  hash: "hash(obj) -> int",
  help: "help([object])",
  hex: "hex(x) -> str",
  id: "id(object) -> int",
  input: "input(prompt='') -> str",
  int: "int(x=0[, base])",
  isinstance: "isinstance(object, classinfo) -> bool",
  issubclass: "issubclass(class, classinfo) -> bool",
  iter: "iter(iterable[, sentinel])",
  len: "len(obj) -> int",
  list: "list([iterable])",
  locals: "locals() -> dict",
  map: "map(function, *iterables)",
  max: "max(iterable[, key, default])",
  memoryview: "memoryview(object)",
  min: "min(iterable[, key, default])",
  next: "next(iterator[, default])",
  object: "object()",
  oct: "oct(x) -> str",
  open: "open(file, mode='r'[, encoding])",
  ord: "ord(c) -> int",
  pow: "pow(base, exp[, mod])",
  print: "print(*objects, sep=' ', end='\\n')",
  property: "property(fget=None, fset=None, fdel=None)",
  range: "range(start, stop[, step])",
  repr: "repr(obj) -> str",
  reversed: "reversed(sequence)",
  round: "round(number[, ndigits])",
  set: "set([iterable])",
  setattr: "setattr(object, name, value)",
  slice: "slice(start, stop[, step])",
  sorted: "sorted(iterable[, key, reverse])",
  staticmethod: "staticmethod(function)",
  str: "str(object='') -> str",
  sum: "sum(iterable[, start=0])",
  super: "super([type[, object-or-type]])",
  tuple: "tuple([iterable])",
  type: "type(object) -> type",
  vars: "vars([object]) -> dict",
  zip: "zip(*iterables, strict=False)",
};

/** Multi-line Python snippets. */
export interface PythonSnippet {
  label: string;
  insertText: string;
  documentation: string;
}

export const PYTHON_SNIPPETS: PythonSnippet[] = [
  {
    label: "def function",
    insertText: "def ${1:function_name}(${2:params}):\n    ${0:pass}",
    documentation: "Define a new function with parameters and body",
  },
  {
    label: "class",
    insertText: "class ${1:ClassName}:\n    def __init__(self, ${2:params}):\n        ${0:pass}",
    documentation: "Define a class with an __init__ constructor",
  },
  {
    label: "if __name__ == '__main__'",
    insertText: 'if __name__ == "__main__":\n    ${0:main()}',
    documentation: "Standard Python entrypoint boilerplate",
  },
  {
    label: "for in range",
    insertText: "for ${1:i} in range(${2:10}):\n    ${0:print(i)}",
    documentation: "Iterate over a numeric range",
  },
  {
    label: "for in iterable",
    insertText: "for ${1:item} in ${2:iterable}:\n    ${0:print(item)}",
    documentation: "Iterate over any iterable",
  },
  {
    label: "while loop",
    insertText: "while ${1:condition}:\n    ${0:pass}",
    documentation: "Repeat while a condition stays true",
  },
  {
    label: "if / elif / else",
    insertText: "if ${1:condition}:\n    ${2:pass}\nelif ${3:other}:\n    ${4:pass}\nelse:\n    ${0:pass}",
    documentation: "Conditional branching",
  },
  {
    label: "try...except",
    insertText: "try:\n    ${1:pass}\nexcept ${2:Exception} as ${3:e}:\n    ${0:print(e)}",
    documentation: "Try-except error handling block",
  },
  {
    label: "try...except...finally",
    insertText: "try:\n    ${1:pass}\nexcept ${2:Exception} as ${3:e}:\n    ${4:print(e)}\nfinally:\n    ${0:pass}",
    documentation: "Error handling with a finally cleanup block",
  },
  {
    label: "with open(...)",
    insertText: 'with open("${1:file.txt}", "${2:r}") as ${3:f}:\n    ${0:data = f.read()}',
    documentation: "Open a file safely with a context manager",
  },
  {
    label: "with context manager",
    insertText: "with ${1:context} as ${2:value}:\n    ${0:pass}",
    documentation: "Use any context manager",
  },
  {
    label: "list comprehension",
    insertText: "[${1:x} for ${1:x} in ${2:iterable} if ${3:condition}]",
    documentation: "Build a list from an iterable",
  },
  {
    label: "dict comprehension",
    insertText: "{${1:k}: ${2:v} for ${3:k}, ${4:v} in ${5:iterable}}",
    documentation: "Build a dictionary from an iterable",
  },
  {
    label: "lambda",
    insertText: "lambda ${1:args}: ${0:expression}",
    documentation: "Anonymous inline function",
  },
  {
    label: "match...case",
    insertText: "match ${1:subject}:\n    case ${2:pattern}:\n        ${3:pass}\n    case _:\n        ${0:pass}",
    documentation: "Structural pattern matching (Python 3.10+)",
  },
  {
    label: "async def",
    insertText: "async def ${1:name}(${2:params}):\n    ${0:pass}",
    documentation: "Define a coroutine function",
  },
  {
    label: "decorator",
    insertText: "def ${1:decorator}(func):\n    def wrapper(*args, **kwargs):\n        ${2:pass}\n        return func(*args, **kwargs)\n    return ${0:wrapper}",
    documentation: "Define a function decorator",
  },
  {
    label: "main guard",
    insertText: "def main():\n    ${1:pass}\n\n\nif __name__ == \"__main__\":\n    main()",
    documentation: "Program entrypoint with a main() function",
  },
  {
    label: "print",
    insertText: "print(${1:message})",
    documentation: "Print values to the console stream",
  },
  {
    label: "import",
    insertText: "import ${1:module}",
    documentation: "Import a module into the current namespace",
  },
  {
    label: "from ... import",
    insertText: "from ${1:module} import ${2:name}",
    documentation: "Import specific names from a module",
  },
];

/** Extract a completion label from a member entry like "sqrt(x) -> float". */
export function memberLabel(entry: string): string {
  const paren = entry.indexOf("(");
  return paren === -1 ? entry : entry.slice(0, paren);
}
